{{/*
Expand the name of the chart.
*/}}
{{- define "traefik-hub.name" -}}
{{- .Chart.Name | trunc 63 | trimSuffix "-" -}}
{{- end -}}

{{/*
Allow customization of the instance label value.
*/}}
{{- define "traefik-hub.instance-name" -}}
{{- printf "%s-%s" .Release.Name .Release.Namespace | trunc 63 | trimSuffix "-" -}}
{{- end -}}

{{/*
Create chart name and version as used by the chart label.
*/}}
{{- define "traefik-hub.chart" -}}
{{- printf "%s-%s" .Chart.Name .Chart.Version | replace "+" "_" | trunc 63 | trimSuffix "-" -}}
{{- end -}}


{{/* Shared labels used for selector */}}
{{/* This is an immutable field: this should not change between upgrade */}}
{{- define "traefik-hub.labelselector" -}}
app.kubernetes.io/name: {{ template "traefik-hub.name" . }}
app.kubernetes.io/instance: {{ template "traefik-hub.instance-name" . }}
{{- end }}


{{/* Shared labels used in metadata */}}
{{- define "traefik-hub.labels" -}}
{{ include "traefik-hub.labelselector" . }}
helm.sh/chart: {{ template "traefik-hub.chart" . }}
app.kubernetes.io/managed-by: {{ .Release.Service }}
{{- with .Values.additionalLabels }}
{{ toYaml . }}
{{- end }}
{{- end }}
