{{- $altNames := list ( printf "admission.%s.svc" .Release.Namespace ) -}}
{{- $cert := genSelfSignedCert ( printf "admission.%s.svc" .Release.Namespace ) nil $altNames 365 -}}

---
apiVersion: v1
kind: Secret
type: kubernetes.io/tls
metadata:
  name: hub-agent-cert
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": "pre-upgrade"
    "helm.sh/hook-delete-policy": "before-hook-creation"
data:
  tls.crt: {{ $cert.Cert | b64enc }}
  tls.key: {{ $cert.Key | b64enc }}

---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: hub-edge-ingress
  namespace: {{ .Release.Namespace }}
webhooks:
  - name: admission.traefik.svc
    clientConfig:
      service:
        name: admission
        namespace: {{ .Release.Namespace }}
        path: /edge-ingress
      caBundle: {{ $cert.Cert | b64enc }}
    sideEffects: None
    admissionReviewVersions:
      - v1
    rules:
      - operations:
          - CREATE
          - UPDATE
          - DELETE
        apiGroups:
          - hub.traefik.io
        apiVersions:
          - v1alpha1
        resources:
          - edgeingresses
        scope: Namespaced

---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: hub-acp
  namespace: {{ .Release.Namespace }}
webhooks:
  - name: admission.traefik.svc
    clientConfig:
      service:
        name: admission
        namespace: {{ .Release.Namespace }}
        path: /acp
      caBundle: {{ $cert.Cert | b64enc }}
    sideEffects: None
    admissionReviewVersions:
      - v1
    rules:
      - operations:
          - CREATE
          - UPDATE
          - DELETE
        apiGroups:
          - hub.traefik.io
        apiVersions:
          - v1alpha1
        resources:
          - accesscontrolpolicies

---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: hub-api
  namespace: {{ .Release.Namespace }}
webhooks:
  - name: hub-agent.traefik.portal
    clientConfig:
      service:
        name: admission
        namespace: {{ .Release.Namespace }}
        path: /api-portal
      caBundle: {{ $cert.Cert | b64enc }}
    sideEffects: None
    admissionReviewVersions:
      - v1
    rules:
      - operations:
          - CREATE
          - UPDATE
          - DELETE
        apiGroups:
          - hub.traefik.io
        apiVersions:
          - v1alpha1
        resources:
          - apiportals
  - name: hub-agent.traefik.gateway
    clientConfig:
      service:
        name: admission
        namespace: {{ .Release.Namespace }}
        path: /api-gateway
      caBundle: {{ $cert.Cert | b64enc }}
    sideEffects: None
    admissionReviewVersions:
      - v1
    rules:
      - operations:
          - CREATE
          - UPDATE
          - DELETE
        apiGroups:
          - hub.traefik.io
        apiVersions:
          - v1alpha1
        resources:
          - apigateways
  - name: hub-agent.traefik.api
    clientConfig:
      service:
        name: admission
        namespace: {{ .Release.Namespace }}
        path: /api
      caBundle: {{ $cert.Cert | b64enc }}
    sideEffects: None
    admissionReviewVersions:
      - v1
    rules:
      - operations:
          - CREATE
          - UPDATE
          - DELETE
        apiGroups:
          - hub.traefik.io
        apiVersions:
          - v1alpha1
        resources:
          - apis
  - name: hub-agent.traefik.collection
    clientConfig:
      service:
        name: admission
        namespace: {{ .Release.Namespace }}
        path: /api-collection
      caBundle: {{ $cert.Cert | b64enc }}
    sideEffects: None
    admissionReviewVersions:
      - v1
    rules:
      - operations:
          - CREATE
          - UPDATE
          - DELETE
        apiGroups:
          - hub.traefik.io
        apiVersions:
          - v1alpha1
        resources:
          - apicollections
  - name: hub-agent.traefik.access
    clientConfig:
      service:
        name: admission
        namespace: {{ .Release.Namespace }}
        path: /api-access
      caBundle: {{ $cert.Cert | b64enc }}
    sideEffects: None
    admissionReviewVersions:
      - v1
    rules:
      - operations:
          - CREATE
          - UPDATE
          - DELETE
        apiGroups:
          - hub.traefik.io
        apiVersions:
          - v1alpha1
        resources:
          - apiaccesses
  - name: hub-agent.traefik.rate-limit
    clientConfig:
      service:
        name: admission
        namespace: {{ .Release.Namespace }}
        path: /api-rate-limit
      caBundle: {{ $cert.Cert | b64enc }}
    sideEffects: None
    admissionReviewVersions:
      - v1
    rules:
      - operations:
          - CREATE
          - UPDATE
          - DELETE
        apiGroups:
          - hub.traefik.io
        apiVersions:
          - v1alpha1
        resources:
          - apiratelimits

---
apiVersion: v1
kind: Service
metadata:
  name: admission
  namespace: {{ .Release.Namespace }}
spec:
  ports:
    - name: https
      port: 443
      targetPort: admission
  selector:
  {{- include "traefik-hub.labelselector" . | nindent 4 }}
