---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "traefik-hub.instance-name" . }}
  labels:
  {{- include "traefik-hub.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "traefik-hub.instance-name" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "traefik-hub.serviceaccount-name" . }}
    namespace: {{ .Release.Namespace }}
