{{- if .Values.autoscaling.maxReplicas }}
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "traefik-hub.name" . }}
  namespace: {{ .Release.Namespace }}
  labels: {{ include "traefik-hub.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: traefik
{{- with .Values.autoscaling }}
  {{- with .minReplicas }}
  minReplicas: {{ . }}
  {{- end }}
  {{- with .maxReplicas }}
  maxReplicas: {{ . }}
  {{- end }}
  {{- with .metrics }}
  metrics: {{ toYaml . | nindent 4 }}
  {{- end }}
  {{- with .behavior }}
  behavior: {{ toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
{{- end }}
