---
apiVersion: v1
kind: Service
metadata:
  name: traefik
  namespace: {{ .Release.Namespace }}
  labels:
  {{- include "traefik-hub.labels" . | nindent 4 }}
  annotations:
  {{- with .Values.service.annotations }}
  {{ toYaml . | indent 2 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  loadBalancerClass: {{ .Values.service.loadBalancerClass }}
  selector:
     {{- include "traefik-hub.labelselector" . | nindent 6 }}
  ports:
    - port: 80
      name: "web"
      targetPort: web
      protocol: TCP
    - port: 443
      name: "websecure"
      targetPort: websecure
      protocol: TCP
    - port: 8443
      name: grpc
      targetPort: grpc
