---
kind: ServiceAccount
apiVersion: v1
metadata:
  name: {{ .Values.serviceAccountName }}
  namespace: {{ .Release.Namespace }}
  labels:
  {{- include "traefik-hub.labels" . | nindent 4 }}
automountServiceAccountToken: false
