---
kind: ServiceAccount
apiVersion: v1
metadata:
  name: {{ include "traefik-hub.serviceaccount-name" . }}
  namespace: {{ .Release.Namespace }}
  labels: {{- include "traefik-hub.labels" . | nindent 4 }}
automountServiceAccountToken: false
