---
name: Test

on:
  workflow_call:
  workflow_dispatch:
  pull_request:
    paths:
      - 'chart/**'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
      - name: Lint Chart
        run: make lint-chart

      - name: Test Chart
        run: make test-chart
